import { createTypes } from 'reduxsauce'

export default createTypes(
  `
    FETCH_AIRLINES
    FETCH_AIRLINES_SUCCESS
    FETCH_AIRLINES_FAILURE

    FILTER_AIRLINES

    FETCH_AIRLINE
    FETCH_AIRLINE_SUCCESS
    FETCH_AIRLINE_FAILURE

    POST_AIRLINE
    POST_AIRLINE_SUCCESS
    POST_AIRLINE_FAILURE

    PUT_AIRLINE
    PUT_AIRLINE_SUCCESS
    PUT_AIRLINE_FAILURE

    PATCH_AIRLINE
    PATCH_AIRLINE_SUCCESS
    PATCH_AIRLINE_FAILURE

    DELETE_AIRLINE
    DELETE_AIRLINE_SUCCESS
    DELETE_AIRLINE_FAILURE

    DISABLE_AIRLINE
    DISABLE_AIRLINE_SUCCESS
    DISABLE_AIRLINE_FAILURE

    ENABLE_AIRLINE
    ENABLE_AIRLINE_SUCCESS
    ENABLE_AIRLINE_FAILURE

    SET_SELECTED_AIRLINE

    RESET_AIRLINE
  `,
)