import { createTypes } from 'reduxsauce'

export default createTypes(
  `
    FETCH_PRODUCTS
    FETCH_PRODUCTS_SUCCESS
    FETCH_PRODUCTS_FAILURE

    FILTER_PRODUCTS

    FETCH_PRODUCT
    FETCH_PRODUCT_SUCCESS
    FETCH_PRODUCT_FAILURE

    POST_PRODUCT
    POST_PRODUCT_SUCCESS
    POST_PRODUCT_FAILURE

    PUT_PRODUCT
    PUT_PRODUCT_SUCCESS
    PUT_PRODUCT_FAILURE

    DELETE_PRODUCT
    DELETE_PRODUCT_SUCCESS
    DELETE_PRODUCT_FAILURE

    SET_SELECTED_PRODUCT

    RESET_PRODUCT
  `,
)